# Generated by Django 5.0.7 on 2025-12-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_remove_experience_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.CharField(blank=True, help_text='Separate skills with commas (e.g. Python, CSS, AWS)', max_length=200),
        ),
    ]
