# Generated by Django 5.0.7 on 2026-06-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='section',
            field=models.CharField(blank=True, help_text='Optional heading such as Toppings or Bibimbap sauce.', max_length=60),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_credit',
            field=models.CharField(blank=True, help_text='For example: Sous Chef / CC BY 2.0', max_length=150),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_credit_url',
            field=models.URLField(blank=True, help_text='Link to the image source or licence page.'),
        ),
    ]
