# Generated by Django 5.0.7 on 2026-06-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_section_recipe_image_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source_name',
            field=models.CharField(blank=True, help_text='Optional label for the original recipe source.', max_length=120),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, help_text='Link to the original recipe, video, or inspiration.'),
        ),
    ]
